### PR TITLE
Sequence diagram

### PR DESCRIPTION
**Pull request by hizmailovich**
## PR-Codex overview
This PR adds a new sequence diagram for the Jira Integration API.

### Detailed summary
- Added a new sequence diagram in `diagrams/sequence.puml`.
- The diagram showcases the flow of data between the API, Jira, and Harvest.
- The diagram includes the use of a token for authentication.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by hizmailovich** [comment]
image

**Comment by h1alexbel** [comment]
@hizmailovich where is a token for JIRA?

**Comment by hizmailovich** [comment]
image

**Review by h1alexbel — APPROVED** [review]

**Comment by hizmailovich** [comment]
@rultor merge

**Pull request merged**
